language: ruby
rvm:
  - 2.3.1

env:
  matrix:
    – DB=sqlite
    – DB=postgresq

postgres:
  adapter: postgresql
  database: my_database_test
  username: postgres

before_script:
  – psql -c ‘create database my_database_test;’ -U postgres
  – "rake db:migrate"

script:
  – RAILS_ENV=test bundle exec rake –trace db:migrate spec