language: ruby
rvm:
  - 2.3.1-p112

env:
– DB=sqlite
– DB=postgresql

before_script:
– psql -c ‘create database my_database_test;’ -U postgres

script:
– RAILS_ENV=test bundle exec rake –trace db:migrate spec