language: ruby
sudo: true

rvm:
  - 2.3.1

env:
  matrix:
    – DB=postgresql

branches:
    only:
        - master

services:
  - postgresql
  - redis-server

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c ‘create database my_database_test;’ -U postgres
