# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Port.create(name: "Inkoo")
Port.create(name: "Kokkola")
Port.create(name: "Pargas")
Port.create(name: "Jakobstad")
Port.create(name: "Pori")
Port.create(name: "Rauma")
Port.create(name: "Antwerp")
Port.create(name: "Husum SWE")
Port.create(name: "Kunda")
Port.create(name: "Koping")
Port.create(name: "Lulea")
Port.create(name: "Moerdjik")
Port.create(name: "Storugns")
Port.create(name: "Szczecin")
Port.create(name: "Verdal")
Port.create(name: "Uusikaupunki")
Port.create(name: "Norrkoping")
Port.create(name: "Landskrona")
Port.create(name: "Klaipeda")
Port.create(name: "Kolding")
Port.create(name: "Rostock")
Port.create(name: "Paldiski")
Port.create(name: "Lubeck")
Port.create(name: "Åhus")
Port.create(name: "Tallinna")
Port.create(name: "Hamina")
Port.create(name: "Skelleftehamn")
Port.create(name: "Piteå")
Port.create(name: "Kaskinen")
Port.create(name: "Lappeenranta")
Port.create(name: "Savonlinna")
Port.create(name: "Korsør")
Port.create(name: "Flensburg")
Port.create(name: "Gdansk")
Port.create(name: "Wismar")
Port.create(name: "Rendsburg")
Port.create(name: "Vierow")
Port.create(name: "Husum DE")
Port.create(name: "Klintehamn")
Port.create(name: "Holmsund")
Port.create(name: "Mariehamn")
Port.create(name: "Grenå")
Port.create(name: "Kalundborg")
Port.create(name: "Köge")
Port.create(name: "Randers")
Port.create(name: "Skive")
Port.create(name: "Ålborg")
Port.create(name: "Århus")
